t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: aws-sqs
  customPackage: com.epion_t3.aws.sqs
  summary:
    - lang: ja_JP
      contents: "AWSのSQSへのアクセスを行う機能を提供します。"
  description:
    - lang: ja_JP
      contents: "AmazonWebService（AWS）のSimpleQueueService（SQS）への各種アクセスを行う機能を提供します。事前データの配置、エビデンスの取得などに利用できるPUT、GETを代表とした機能です。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # AwsSqsSendMessage
  ##########################
  - id: AwsSqsSendMessage
    evidenceCommand: false
    summary:
      - lang: ja_JP
        contents: "SQSに対してメッセージの送信を行います。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "SQS「${target}」に対してメッセージを送信します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "SQSに対してメッセージの送信を行います。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "メッセージボディと属性を指定可能です。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "メッセージグループID、メッセージ重複IDの設定については任意の値の設定と自動設定もサポートします。"
      - order: 4
        summary:
          - lang: ja_JP
            contents: "それぞれの値について変数のバインドが適用可能です。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsSqsSendMessage」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 6
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするSQSのEndpoint"
      - order: 7
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするメッセージ"
      - order: 8
        name: messageGroupId
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "メッセージグループID"
      - order: 9
        name: messageDeduplicationId
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "メッセージ重複排除ID"
      - order: 10
        name: autoGenerateMessageGroupId
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "メッセージグループIDの自動生成フラグ <1><2><3>"
        description:
          - lang: ja_JP
            contents: "真偽値 true or false で指定します。"
          - lang: ja_JP
            contents: "メッセージグループIDが設定されていた場合、そちらが優先されます。"
          - lang: ja_JP
            contents: "メッセージグループIDの生成はUUIDで行われます。"
      - order: 11
        name: autoMessageDeduplicationId
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "メッセージ重複排除IDの自動生成フラグ <4><5><6>"
        description:
          - lang: ja_JP
            contents: "真偽値 true or false で指定します。"
          - lang: ja_JP
            contents: "メッセージ重複排除IDが設定されていた場合、そちらが優先されます。"
          - lang: ja_JP
            contents: "メッセージ重複排除IDの生成はUUIDで行われます。"
  ##########################
  # AwsSqsReceiveMessage
  ##########################
  - id: AwsSqsReceiveMessage
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "SQSからメッセージの取得を行います。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "SQS「${target}」からメッセージを受信します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "SQSからメッセージの取得を行います。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "取得されたメッセージは、エビデンスとして保存します。ファイル名は「receiveMessages.json」で固定です。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "受信したメッセージについて削除が必要な場合は削除処理をこのコマンド中に実施します。"
      - order: 4
        summary:
          - lang: ja_JP
            contents: "可視性タイムアウトの設定が可能です。"
      - order: 5
        summary:
          - lang: ja_JP
            contents: "Waitタイムアウトの設定が可能です。ロングポーリングへの利用が想定している利用方法です。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsSqsReceiveMessage」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 6
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするSQSのEndpoint"
      - order: 7
        name: maxNumberOfMessages
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "同時に受信するメッセージの数。デフォルトは1です。10までの値で指定してください。"
      - order: 8
        name: visibilityTimeout
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "可視性タイムアウトの秒数を指定してください。"
      - order: 9
        name: waitTimeSeconds
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "Waitタイムアウトの秒数を指定してください。"
      - order: 10
        name: deleteMessage
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "受信したメッセージをQueueから削除するかの指定。デフォルトは「false」となり削除しません。"
#####################################
# メッセージ定義
#####################################
messages:
  - id: com.epion_t3.aws.sqs.err.9001
    message:
      - lang: ja_JP
        contents: "対象（target）のEndpointへのメッセージ送信に失敗しました.SQS:{0}"
  - id: com.epion_t3.aws.sqs.err.9002
    message:
      - lang: ja_JP
        contents: "対象（target）のEndpointからのメッセージ受信に失敗しました.SQS:{0}"
  - id: com.epion_t3.aws.sqs.err.9003
    message:
      - lang: ja_JP
        contents: "対象（target）のEndpointからのメッセージ削除に失敗しました.SQS:{0}"
